version: '3.8'

services:
  # --- CUSTOM ALPINE HADOOP 3.5.0 NAMENODE ---
  namenode:
    image: owuordickson/hdfs-base:latest
    container_name: namenode
    hostname: namenode
    env_file:
      - ./configs/hadoop.env
    environment:
      HADOOP_NODE_TYPE: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/opt/hadoop/dfs/name
    networks:
      - net_bd

  # --- CUSTOM ALPINE HADOOP 3.5.0 DATANODE ---
  datanode:
    image: owuordickson/hdfs-base:latest
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    env_file:
      - ./configs/hadoop.env
    environment:
      HADOOP_NODE_TYPE: datanode
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/opt/hadoop/dfs/data
    networks:
      - net_bd

  # --- APACHE KAFKA BROKER ---
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRAFT CORE INITIALIZATION ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      
      # --- PROTOCOL & LISTENER REGISTRY ---
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_LISTENERS: 'CLIENT://:9092,EXTERNAL://:9093,CONTROLLER://:9094'
      
      # --- THE ROUTING TABLE GIVEN TO NODE-RED & PYSPARK ---
      KAFKA_ADVERTISED_LISTENERS: 'CLIENT://kafka:9092,EXTERNAL://localhost:9093'
      
      # --- INTER-CLUSTER ORCHESTRATION ---
      KAFKA_INTER_BROKER_LISTENER_NAME: 'CLIENT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      
      # --- FEATURES ---
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - net_bd

  # --- SPARK 4.1.2 ENGINE ---
  spark-master:
    image: apache/spark:4.1.2-python3
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./code/spark-apps:/home/
    networks:
      - net_bd

  spark-worker:
    image: apache/spark:4.1.2-python3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    volumes:
      - ./code/spark-apps:/home/
    networks:
      - net_bd

  # --- APACHE ZEPPELIN NOTEBOOK ---
  zeppelin:
    image: apache/zeppelin:0.12.1
    container_name: zeppelin
    ports:
      - "8082:8080"  # Exposes Zeppelin Web UI on local port 8082
    environment:
      MASTER: "spark://spark-master:7077"
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_MASTER_URL: "spark://spark-master:7077"
      CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
      HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
      SPARK_HOME: /opt/spark
    volumes:
      - zeppelin_notebooks:/opt/zeppelin/notebook
    depends_on:
      - spark-master
      - namenode
    networks:
      - net_bd

  # --- NODE-RED DATA GENERATOR ---
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1881:1880"  # Node-RED Visual Workflow UI
    volumes:
      - nodered_data:/data
    depends_on:
      - kafka
    networks:
      - net_bd

volumes:
  hadoop_namenode:
  hadoop_datanode:
  zeppelin_notebooks:
  nodered_data:

networks:
  net_bd:
    driver: bridge
