services:

  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1881:1880"
    volumes:
      - nodered_data:/data
    networks:
      - net_bd

  namenode:
    image: owuordickson/hdfs-namenode:0.0.1
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      CLUSTER_NAME: test
    env_file:
      - ./configs/hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - net_bd

  datanode:
    image: owuordickson/hdfs-datanode:0.0.1
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./configs/hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - net_bd

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    user: root
    depends_on:
      - namenode
      - datanode
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8083:8080"
    environment:
      SPARK_MASTER_HOST: spark-master

      # HDFS
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop

    volumes:
      - ./src/spark-apps:/opt/spark/work-dir
      - ./configs/hadoop:/opt/hadoop/etc/hadoop:ro
      - ./configs/spark/jars_dir:/opt/spark/ivy
    networks:
      - net_bd

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    hostname: spark-worker
    user: root
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2

      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop

    volumes:
      - ./src/spark-apps:/opt/spark/work-dir
      - ./configs/hadoop:/opt/hadoop/etc/hadoop:ro
      - ./configs/spark/jars_dir:/opt/spark/ivy
    networks:
      - net_bd

  zeppelin:
    image: apache/zeppelin:0.11.2
    container_name: zeppelin
    depends_on:
      - spark-master
      - namenode
    ports:
      - "8082:8080"
    environment:
      MASTER: spark://spark-master:7077
      SPARK_MASTER: spark://spark-master:7077
      SPARK_MASTER_URL: spark://spark-master:7077
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HADOOP_CONF_DIR: /opt/hadoop/etc/hadoop
    volumes:
      - zeppelin_notebook:/opt/zeppelin/notebook
      - zeppelin_logs:/opt/zeppelin/logs
      - ./configs/hadoop:/opt/hadoop/etc/hadoop:ro
    networks:
      - net_bd

  zookeeper:
    image: apache/zookeeper:3.9.3
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - net_bd

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - net_bd

volumes:
  nodered_data:
  zeppelin_logs:
  zeppelin_notebook:
  hadoop_namenode:
  hadoop_datanode:

networks:
  net_bd:
    driver: bridge
